version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      # Define pre-build variables.
      # - REPO_NAME=ncompasstv-dashboard  # DEFINE THIS VARIABLE 
      # - ECS_CONTAINER_NAME=dashboard    # DEFINE THIS VARIABLE 
      - AWS_ACCOUNT_ID=`aws sts get-caller-identity --query "Account" --output text`
      # - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      # - IMAGE_TAG=${COMMIT_HASH:=latest}
      # - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME
      # # ECR Authentication.
      # - echo Logging in to Amazon ECR...
      # - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Installing dependencies..."
      - npx npm-force-resolutions
      - npm install
  build:
    on-failure: ABORT
    commands:
      # Get environment name
      - echo $ENV_NAME
      # Build docker images and tag based on build ID.
      - echo Build started on `date`
      - echo "Building angular project..."
      - npm run build -- --configuration $ENV_NAME
      - ls -l /app/dist/dashboard-material
      - echo "DONE!!"
  post_build:
    commands:
      - echo "Updating S3 Content..."
      - echo $ENV_NAME
      - echo $DASHBOARD_S3_BUCKET
      - aws s3 sync dist/dashboard-material/ s3://$DASHBOARD_S3_BUCKET.n-compass.online --delete
      - echo "DONE!!!"
