version: 0.2

env:
    shell: bash

phases:
    install:
        runtime-versions:
            nodejs: 14
    pre_build:
        commands:
            # Define pre-build variables.
            - AWS_ACCOUNT_ID=`aws sts get-caller-identity --query "Account" --output text`
            - npx npm-force-resolutions
            - npm install
    build:
        on-failure: ABORT
        commands:
            # Get environment name
            - echo $ENV_NAME
            # Build docker images and tag based on build ID.
            - echo Build started on `date`
            - echo "Building angular project..."
            - npm run build_env -- --configuration $ENV_NAME
            - ls -l ./dist/dashboard-material/
            - echo "DONE!!"
    post_build:
        commands:
            - echo "Updating S3 Content..."
            - echo $ENV_NAME
            - echo $DASHBOARD_S3_BUCKET
            - aws s3 sync ./dist/dashboard-material/ s3://$DASHBOARD_S3_BUCKET.n-compass.online --delete
            - aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --path '/*'
            - echo "DONE!!!"
