version: '3'
services:
  dashboard:
    container_name: dashboard
    build:
      context: .
    image: 892444632159.dkr.ecr.us-east-1.amazonaws.com/nc-nvir-dev-test-dashboard-01
    environment:
      VIRTUAL_HOST: dashboarddev.ourimage.biz
      
networks:
  default:
    external:
      name: n-compass-proxy