version: '3'
services:
  dashboard:
    container_name: dashboard
    build:
      dockerfile: Dockerfile_$BUILD_ENV
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ncompasstv-dashboard:$BUILD_ENV